services:
  db:
    image: postgres:14
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6713
      POSTGRES_DB: archangel
    volumes:
      - postgres_data_archangel:/var/lib/postgresql/data
    networks:
      - backend

  db_openai_api:
    image: postgres:14
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6713
      POSTGRES_DB: characters
    volumes:
      - postgres_data_characters:/var/lib/postgresql/data
    networks:
      - backend

  archangel:
    build: .
    command: gunicorn Archangel.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  analyse_service:
    build:
      context: ./services/analyse_service
      dockerfile: Dockerfile
    container_name: analyse_service
    ports:
      - "8044:8044"
    depends_on:
      - db_openai_api
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend

  celery_worker:
    build:
      context: ./services/analyse_service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db_openai_api
    command: conda run --no-capture-output -n analyse_service celery -A app.celery_app:celery worker -l INFO --concurrency=3
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/usr/share/nginx/html/static
    depends_on:
      - archangel
    networks:
      - backend

volumes:
  postgres_data_archangel:
  postgres_data_characters:
  static:
  media:

networks:
  backend:
